export const SPEC_TEMPLATES = {
  processor: [
    { key: "core_count", label: "Core Count", type: "text" },
    { key: "thread_count", label: "Thread Count", type: "text" },
    { key: "base_clock", label: "Base Clock", type: "text" },
    { key: "boost_clock", label: "Boost Clock", type: "text" },
    { key: "socket", label: "Socket", type: "text" },
    { key: "tdp", label: "TDP", type: "text" },
    { key: "architecture", label: "Architecture", type: "text" },
    { key: "manufacturing_process", label: "Manufacturing Process", type: "text" },
    { key: "integrated_graphics", label: "Integrated Graphics", type: "text" },
    { key: "max_memory_support", label: "Max Memory Support", type: "text" },
    { key: "memory_type", label: "Memory Type", type: "select", options: ["DDR4", "DDR5", "DDR4 & DDR5", "LPDDR5"] },
    { key: "pcie_version", label: "PCIe Version", type: "select", options: ["PCIe 4.0", "PCIe 5.0"] },
  ],
  graphics_card: [
    { key: "chipset", label: "Chipset", type: "text" },
    { key: "vram", label: "VRAM", type: "text" },
    { key: "vram_type", label: "VRAM Type", type: "select", options: ["GDDR6", "GDDR6X", "GDDR7", "HBM2e"] },
    { key: "core_clock", label: "Core Clock", type: "text" },
    { key: "boost_clock", label: "Boost Clock", type: "text" },
    { key: "cuda_cores", label: "CUDA Cores / Stream Processors", type: "text" },
    { key: "memory_bandwidth", label: "Memory Bandwidth", type: "text" },
    { key: "tdp", label: "TDP", type: "text" },
    { key: "pcie_interface", label: "PCIe Interface", type: "select", options: ["PCIe 4.0 x16", "PCIe 5.0 x16"] },
    { key: "hdmi_ports", label: "HDMI Ports", type: "number" },
    { key: "displayport_ports", label: "DisplayPort Ports", type: "number" },
    { key: "max_resolution", label: "Max Resolution", type: "text" },
    { key: "length", label: "Length (mm)", type: "number" },
    { key: "power_connectors", label: "Power Connectors", type: "text" },
    { key: "recommended_psu", label: "Recommended PSU", type: "text" },
  ],
  memory: [
    { key: "memory_type", label: "Memory Type", type: "select", options: ["DDR4", "DDR5", "DDR3"] },
    { key: "capacity", label: "Capacity", type: "text" },
    { key: "speed", label: "Speed", type: "text" },
    { key: "cas_latency", label: "CAS Latency", type: "text" },
    { key: "voltage", label: "Voltage", type: "text" },
    { key: "form_factor", label: "Form Factor", type: "select", options: ["DIMM", "SO-DIMM"] },
    { key: "rgb", label: "RGB Lighting", type: "select", options: ["Yes", "No"] },
    { key: "heat_spreader", label: "Heat Spreader", type: "select", options: ["Yes", "No"] },
    { key: "ecc", label: "ECC Support", type: "select", options: ["Yes", "No"] },
  ],
  motherboard: [
    { key: "socket", label: "CPU Socket", type: "text" },
    { key: "chipset", label: "Chipset", type: "text" },
    { key: "form_factor", label: "Form Factor", type: "select", options: ["ATX", "Micro-ATX", "Mini-ITX", "E-ATX"] },
    { key: "memory_type", label: "Memory Type", type: "select", options: ["DDR4", "DDR5"] },
    { key: "max_memory", label: "Max Memory", type: "text" },
    { key: "memory_slots", label: "Memory Slots", type: "number" },
    { key: "pcie_x16_slots", label: "PCIe x16 Slots", type: "number" },
    { key: "m2_slots", label: "M.2 Slots", type: "number" },
    { key: "sata_ports", label: "SATA Ports", type: "number" },
    { key: "usb_ports", label: "USB Ports", type: "text" },
    { key: "wifi", label: "WiFi", type: "select", options: ["Yes", "No"] },
    { key: "bluetooth", label: "Bluetooth", type: "select", options: ["Yes", "No"] },
  ],
  storage: [
    { key: "storage_type", label: "Storage Type", type: "select", options: ["SSD", "HDD", "NVMe SSD", "External"] },
    { key: "capacity", label: "Capacity", type: "text" },
    { key: "form_factor", label: "Form Factor", type: "select", options: ["2.5\"", "3.5\"", "M.2 2280", "M.2 2242"] },
    { key: "interface", label: "Interface", type: "select", options: ["SATA III", "NVMe PCIe 3.0", "NVMe PCIe 4.0", "NVMe PCIe 5.0", "USB"] },
    { key: "read_speed", label: "Read Speed", type: "text" },
    { key: "write_speed", label: "Write Speed", type: "text" },
    { key: "rpm", label: "RPM", type: "select", options: ["5400", "7200", "10000", "N/A"] },
  ],
  power_supply: [
    { key: "wattage", label: "Wattage", type: "text" },
    { key: "efficiency_rating", label: "Efficiency Rating", type: "select", options: ["80+ White", "80+ Bronze", "80+ Silver", "80+ Gold", "80+ Platinum", "80+ Titanium"] },
    { key: "modular", label: "Modular", type: "select", options: ["Full Modular", "Semi Modular", "Non-Modular"] },
    { key: "form_factor", label: "Form Factor", type: "select", options: ["ATX", "SFX", "TFX"] },
    { key: "fan_size", label: "Fan Size (mm)", type: "text" },
    { key: "pcie_connectors", label: "PCIe Connectors", type: "text" },
    { key: "sata_connectors", label: "SATA Connectors", type: "text" },
    { key: "protection_features", label: "Protection Features", type: "text" },
  ],
  case: [
    { key: "form_factor", label: "Form Factor", type: "select", options: ["Full Tower", "Mid Tower", "Mini Tower", "SFF", "Wall Mount"] },
    { key: "motherboard_support", label: "Motherboard Support", type: "text" },
    { key: "max_gpu_length", label: "Max GPU Length (mm)", type: "number" },
    { key: "max_cooler_height", label: "Max CPU Cooler Height (mm)", type: "number" },
    { key: "fan_support", label: "Fan Support", type: "text" },
    { key: "radiator_support", label: "Radiator Support", type: "text" },
    { key: "drive_bays", label: "Drive Bays", type: "text" },
    { key: "side_panel", label: "Side Panel", type: "select", options: ["Tempered Glass", "Mesh", "Solid", "Acrylic"] },
    { key: "rgb", label: "RGB Lighting", type: "select", options: ["Yes", "No"] },
    { key: "weight", label: "Weight (kg)", type: "number" },
    { key: "color", label: "Color", type: "text" },
  ],
  cooling: [
    { key: "cooler_type", label: "Cooler Type", type: "select", options: ["Air Cooler", "AIO Liquid Cooler", "Custom Loop", "Thermal Paste"] },
    { key: "fan_size", label: "Fan Size (mm)", type: "text" },
    { key: "fan_speed", label: "Fan Speed (RPM)", type: "text" },
    { key: "noise_level", label: "Noise Level (dBA)", type: "text" },
    { key: "socket_compatibility", label: "Socket Compatibility", type: "text" },
    { key: "tdp_rating", label: "TDP Rating", type: "text" },
    { key: "radiator_size", label: "Radiator Size", type: "select", options: ["120mm", "240mm", "280mm", "360mm", "420mm", "N/A"] },
    { key: "material", label: "Material", type: "text" },
    { key: "rgb", label: "RGB Lighting", type: "select", options: ["Yes", "No"] },
  ],
  prebuilt_pc: [
    { key: "processor", label: "Processor", type: "text" },
    { key: "graphics_card", label: "Graphics Card", type: "text" },
    { key: "memory", label: "Memory", type: "text" },
    { key: "storage", label: "Storage", type: "text" },
    { key: "motherboard", label: "Motherboard", type: "text" },
    { key: "power_supply", label: "Power Supply", type: "text" },
    { key: "cooling", label: "Cooling System", type: "text" },
    { key: "case", label: "Case", type: "text" },
    { key: "warranty", label: "Warranty", type: "text" },
    { key: "operating_system", label: "Operating System", type: "text" },
  ],
  accessories: [
    { key: "accessory_type", label: "Accessory Type", type: "select", options: ["Cable", "Adapter", "Mount", "Tool Kit", "Cleaning Kit", "Other"] },
    { key: "compatibility", label: "Compatibility", type: "text" },
    { key: "material", label: "Material", type: "text" },
    { key: "color", label: "Color", type: "text" },
    { key: "length", label: "Length", type: "text" },
  ],
  software: [
    { key: "software_type", label: "Software Type", type: "select", options: ["Operating System", "Antivirus", "Productivity", "Game", "Driver"] },
    { key: "license_type", label: "License Type", type: "select", options: ["Full", "OEM", "Subscription", "Free"] },
    { key: "platform", label: "Platform", type: "select", options: ["Windows", "macOS", "Linux", "Multi-Platform"] },
    { key: "version", label: "Version", type: "text" },
    { key: "download_size", label: "Download Size", type: "text" },
  ],
  networking: [
    { key: "device_type", label: "Device Type", type: "select", options: ["Router", "Switch", "Access Point", "Network Card", "Modem", "Range Extender"] },
    { key: "wifi_standard", label: "WiFi Standard", type: "select", options: ["WiFi 5 (802.11ac)", "WiFi 6 (802.11ax)", "WiFi 6E", "WiFi 7"] },
    { key: "speed", label: "Speed", type: "text" },
    { key: "ports", label: "Ports", type: "text" },
    { key: "frequency_band", label: "Frequency Band", type: "text" },
    { key: "antenna_count", label: "Antenna Count", type: "number" },
  ],
};

export const COMPATIBILITY_FIELDS = {
  processor: [
    { key: "socket", label: "Socket Compatibility", type: "select", options: ["LGA1700", "LGA1851", "AM4", "AM5", "LGA1200", "LGA2066", "sTRX4"] },
    { key: "chipset", label: "Chipset Compatibility", type: "text" },
  ],
  graphics_card: [
    { key: "pcie_version", label: "PCIe Version", type: "select", options: ["PCIe 3.0", "PCIe 4.0", "PCIe 5.0"] },
    { key: "recommended_psu_min", label: "Min Recommended PSU", type: "text" },
  ],
  memory: [
    { key: "memory_type", label: "Memory Type", type: "select", options: ["DDR4", "DDR5", "DDR3"] },
    { key: "form_factor", label: "Form Factor", type: "select", options: ["DIMM", "SO-DIMM"] },
  ],
};
