export const ROUTES = {
  LOGIN: "/login",
  DASHBOARD: "/admin/dashboard",
  PRODUCTS: "/admin/products",
  PRODUCT_NEW: "/admin/products/new",
  PRODUCT_EDIT: "/admin/products/:id/edit",
  CATEGORIES: "/admin/categories",
  CATEGORY_NEW: "/admin/categories/new",
  CATEGORY_EDIT: "/admin/categories/:id/edit",
  BRANDS: "/admin/brands",
  BRAND_NEW: "/admin/brands/new",
  BRAND_EDIT: "/admin/brands/:id/edit",
  PREBUILT: "/admin/prebuilt",
  PREBUILT_NEW: "/admin/prebuilt/new",
  PREBUILT_EDIT: "/admin/prebuilt/:id/edit",
  ORDERS: "/admin/orders",
  ORDER_DETAILS: "/admin/orders/:id",
  COUPONS: "/admin/coupons",
  COUPON_NEW: "/admin/coupons/new",
  COUPON_EDIT: "/admin/coupons/:id/edit",
  REVIEWS: "/admin/reviews",
  USERS: "/admin/users",
  USER_DETAILS: "/admin/users/:id",
  SETTINGS: "/admin/settings",
  PROFILE: "/admin/profile",
};
