export const PERMISSIONS = {
  users: {
    create: 'users.create',
    read: 'users.read',
    update: 'users.update',
    delete: 'users.delete',
    list: 'users.list',
    block: 'users.block',
    deactivate: 'users.deactivate',
    assignRole: 'users.role.assign',
  },
  products: {
    create: 'products.create',
    read: 'products.read',
    update: 'products.update',
    delete: 'products.delete',
    list: 'products.list',
    archive: 'products.archive',
    manageStock: 'products.stock.manage',
  },
  categories: {
    create: 'categories.create',
    read: 'categories.read',
    update: 'categories.update',
    delete: 'categories.delete',
    list: 'categories.list',
  },
  brands: {
    create: 'brands.create',
    read: 'brands.read',
    update: 'brands.update',
    delete: 'brands.delete',
    list: 'brands.list',
  },
  prebuilts: {
    create: 'prebuilts.create',
    read: 'prebuilts.read',
    update: 'prebuilts.update',
    delete: 'prebuilts.delete',
    list: 'prebuilts.list',
    archive: 'prebuilts.archive',
  },
  bundles: {
    create: 'bundles.create',
    read: 'bundles.read',
    update: 'bundles.update',
    delete: 'bundles.delete',
    list: 'bundles.list',
    archive: 'bundles.archive',
    toggleStatus: 'bundles.status.toggle',
  },
  orders: {
    create: 'orders.create',
    read: 'orders.read',
    update: 'orders.update',
    delete: 'orders.delete',
    list: 'orders.list',
    manageStatus: 'orders.status.manage',
    managePaymentStatus: 'orders.paymentStatus.manage',
    cancel: 'orders.cancel',
    process: 'orders.process',
    ship: 'orders.ship',
    deliver: 'orders.deliver',
    return: 'orders.return',
    refund: 'orders.refund',
  },
  coupons: {
    create: 'coupons.create',
    read: 'coupons.read',
    update: 'coupons.update',
    delete: 'coupons.delete',
    list: 'coupons.list',
  },
  deals: {
    create: 'deals.create',
    read: 'deals.read',
    update: 'deals.update',
    delete: 'deals.delete',
    list: 'deals.list',
    toggleStatus: 'deals.status.toggle',
  },
  reviews: {
    create: 'reviews.create',
    read: 'reviews.read',
    update: 'reviews.update',
    delete: 'reviews.delete',
    list: 'reviews.list',
    moderate: 'reviews.moderate',
    toggleFeatured: 'reviews.featured.toggle',
    reply: 'reviews.reply',
    dismissReports: 'reviews.reports.dismiss',
    clearSpam: 'reviews.spam.clear',
  },
  support: {
    createTicket: 'support.tickets.create',
    read: 'support.tickets.read',
    update: 'support.tickets.update',
    delete: 'support.tickets.delete',
    list: 'support.tickets.list',
    reply: 'support.tickets.reply',
    assign: 'support.tickets.assign',
    updateStatus: 'support.tickets.status.update',
    updatePriority: 'support.tickets.priority.update',
  },
  settings: {
    read: 'settings.read',
    update: 'settings.update',
    managePaymentKeys: 'settings.paymentKeys.manage',
  },
  dashboard: {
    read: 'dashboard.read',
    sales: 'dashboard.sales.read',
    recentOrders: 'dashboard.recentOrders.read',
    lowStock: 'dashboard.lowStock.read',
    topProducts: 'dashboard.topProducts.read',
    orderBreakdown: 'dashboard.orderBreakdown.read',
  },
  notifications: {
    read: 'notifications.read',
    markRead: 'notifications.markRead',
    markAllRead: 'notifications.markAllRead',
    delete: 'notifications.delete',
    list: 'notifications.list',
    adminList: 'notifications.admin.list',
  },
  search: {
    public: 'search.public',
    admin: 'search.admin',
  },
  faqs: {
    read: 'faqs.read',
    list: 'faqs.list',
    create: 'faqs.create',
    update: 'faqs.update',
    delete: 'faqs.delete',
  },
  newsletter: {
    subscribe: 'newsletter.subscribe',
    unsubscribe: 'newsletter.unsubscribe',
    list: 'newsletter.list',
    read: 'newsletter.read',
    update: 'newsletter.update',
    delete: 'newsletter.delete',
    export: 'newsletter.export',
  },
  stockAlerts: {
    subscribe: 'stockAlerts.subscribe',
    read: 'stockAlerts.read',
    cancel: 'stockAlerts.cancel',
  },
  addresses: {
    create: 'addresses.create',
    read: 'addresses.read',
    update: 'addresses.update',
    delete: 'addresses.delete',
    list: 'addresses.list',
  },
  builds: {
    create: 'builds.create',
    read: 'builds.read',
    update: 'builds.update',
    delete: 'builds.delete',
    list: 'builds.list',
    validate: 'builds.validate',
    duplicate: 'builds.duplicate',
    addToCart: 'builds.addToCart',
    adminList: 'builds.admin.list',
    analytics: 'builds.analytics.read',
    compatibilityIssues: 'builds.compatibilityIssues.read',
    settingsRead: 'builds.settings.read',
    settingsUpdate: 'builds.settings.update',
  },
  uploads: {
    image: 'uploads.image',
  },
  ai: {
    chat: 'ai.chat',
  },
  roles: {
    manage: 'roles.manage',
  },
  permissions: {
    manage: 'permissions.manage',
  },
  audit: {
    logsRead: 'audit.logs.read',
  },
};

export const PROTECTED_PERMISSIONS = [
  'roles.manage',
  'permissions.manage',
  'audit.logs.read',
  'settings.paymentKeys.manage',
  'users.role.assign',
  'users.delete',
];

export const PERMISSION_MODULE_MAP = {
  users: Object.values(PERMISSIONS.users),
  products: Object.values(PERMISSIONS.products),
  categories: Object.values(PERMISSIONS.categories),
  brands: Object.values(PERMISSIONS.brands),
  prebuilts: Object.values(PERMISSIONS.prebuilts),
  bundles: Object.values(PERMISSIONS.bundles),
  orders: Object.values(PERMISSIONS.orders),
  coupons: Object.values(PERMISSIONS.coupons),
  deals: Object.values(PERMISSIONS.deals),
  reviews: Object.values(PERMISSIONS.reviews),
  support: Object.values(PERMISSIONS.support),
  settings: Object.values(PERMISSIONS.settings),
  dashboard: Object.values(PERMISSIONS.dashboard),
  notifications: Object.values(PERMISSIONS.notifications),
  search: Object.values(PERMISSIONS.search),
  faqs: Object.values(PERMISSIONS.faqs),
  newsletter: Object.values(PERMISSIONS.newsletter),
  stockAlerts: Object.values(PERMISSIONS.stockAlerts),
  addresses: Object.values(PERMISSIONS.addresses),
  builds: Object.values(PERMISSIONS.builds),
  uploads: Object.values(PERMISSIONS.uploads),
  ai: Object.values(PERMISSIONS.ai),
  roles: Object.values(PERMISSIONS.roles),
  permissions: Object.values(PERMISSIONS.permissions),
  audit: Object.values(PERMISSIONS.audit),
};